source 'https://rubygems.org'

ruby '2.5.1'

gem 'capybara'
gem 'chromedriver-helper'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'sinatra'
gem 'simplecov', require: false
  gem 'simplecov-console', require: false